/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.stockreserve.telas;

import java.awt.BorderLayout;
import java.awt.Color;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
import java.sql.*;
import br.com.stockreserve.dal.ModuloConexao;

/**
 *
 * @author Felipe
 */
public class TelaRelatorioVendas extends javax.swing.JInternalFrame {
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form TelaRelatorioVendas
     */
    public TelaRelatorioVendas() {
        initComponents();
        conexao = ModuloConexao.conector();
        graficoBarra();
    }
    
    //Método para a criação do grafico da quantidade de vendas
    public void graficoBarra(){
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(200, "Quantidade", "1");
        dataset.setValue(150, "Quantidade", "2");
        dataset.setValue(18, "Quantidade", "3");
        dataset.setValue(100, "Quantidade", "4");
        dataset.setValue(80, "Quantidade", "5");
        dataset.setValue(250, "Quantidade", "6");
        dataset.setValue(250, "Quantidade", "7");
        dataset.setValue(260, "Quantidade", "8");
        dataset.setValue(150, "Quantidade", "9");
        dataset.setValue(150, "Quantidade", "10");
        dataset.setValue(150, "Quantidade", "11");
        dataset.setValue(150, "Quantidade", "12");
        
        JFreeChart chart = ChartFactory.createBarChart("Vendas Realizadas","Mês","Quantidade", 
                dataset, PlotOrientation.VERTICAL, false,true,false);
        
        CategoryPlot categoryPlot = chart.getCategoryPlot();
        //categoryPlot.setRangeGridlinePaint(Color.BLUE);
        categoryPlot.setBackgroundPaint(Color.WHITE);
        BarRenderer renderer = (BarRenderer) categoryPlot.getRenderer();
        Color clr3 = new Color(204,0,51);
        renderer.setSeriesPaint(0, clr3);
        
        ChartPanel barpChartPanel = new ChartPanel(chart);
        panelGraficoBarra.removeAll();
        panelGraficoBarra.add(barpChartPanel, BorderLayout.CENTER);
        panelGraficoBarra.validate();
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblVendedores = new javax.swing.JTable();
        txtVendPesquisar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        dcPesquisarData = new com.toedter.calendar.JDateChooser();
        panelGraficoBarra = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Relatório de Vendas");
        setPreferredSize(new java.awt.Dimension(1002, 336));
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblVendedores = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int ColIndex){
                return false;
            }
        };
        tblVendedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome Vendedor", "Data", "Valor Venda", "ID Nota Fiscal"
            }
        ));
        jScrollPane2.setViewportView(tblVendedores);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 550, 280));
        getContentPane().add(txtVendPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 220, -1));

        jLabel1.setText("Buscar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 40, -1));

        dcPesquisarData.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(dcPesquisarData, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, 110, -1));

        panelGraficoBarra.setLayout(new java.awt.BorderLayout());
        getContentPane().add(panelGraficoBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 300));

        setBounds(0, 0, 1000, 631);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dcPesquisarData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelGraficoBarra;
    private javax.swing.JTable tblVendedores;
    private javax.swing.JTextField txtVendPesquisar;
    // End of variables declaration//GEN-END:variables
}
